-- AddDropSortIndexes (20260918032350)
--
-- Adds IX_Drop_Created and IX_Drop_Date on [Drops].
--
-- WHY
-- Production sessions were sitting in RESOURCE_SEMAPHORE waits (~21.8s, 21.8s,
-- 24.3s, suspended) -- queueing for a query memory grant before execution even
-- begins. That is the ~25 second constant seen across unrelated queries, and it
-- is why the union rewrite (533x fewer logical reads) changed nothing: the wait
-- happens before the query runs, so query cost is irrelevant to it.
--
-- Memory grants are driven mainly by Sort and Hash operators. The feeds sort on
-- columns with no index:
--     home feed  ORDER BY [Created] DESC   (chronological: false)
--     storyline  ORDER BY [Date]           (chronological: true)
-- so every page requested a grant large enough to sort the whole visible set.
-- Indexing the sort columns removes the Sort operator and most of the grant.
--
-- SQL Server can scan an ascending index backwards, so a single ascending index
-- serves ORDER BY ... DESC. No descending index is needed.
--
-- See docs/investigations/2026-09-09-gettimeline-sql-timeout.md, Round 7.
--
-- BEFORE RUNNING
-- [Drops] is the largest table in the schema. CREATE INDEX locks it while it
-- builds, and the generated script below wraps both statements in ONE
-- transaction, so the lock is held until both complete. Run off-peak. On
-- Enterprise / Azure SQL add WITH (ONLINE = ON) to each CREATE INDEX.
--
-- Generated by: dotnet ef migrations script 20260918020101_AddAdminAudit
--   20260918032350_AddDropSortIndexes --project Domain --startup-project Memento
--   --idempotent
-- DDL below is tool-generated. Do not hand-edit.

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260918032350_AddDropSortIndexes'
)
BEGIN
    CREATE INDEX [IX_Drop_Created] ON [Drops] ([Created]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260918032350_AddDropSortIndexes'
)
BEGIN
    CREATE INDEX [IX_Drop_Date] ON [Drops] ([Date]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260918032350_AddDropSortIndexes'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260918032350_AddDropSortIndexes', N'9.0.8');
END;

COMMIT;
GO

